version: '3.2'
services:
  portainer:
    image: portainer/portainer-ce
    network_mode: "host"
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: