#cloud-config
package_update: false
package_upgrade: false
write_files:
 - path: /root/setup.sh
   content: |
     #!/bin/bash
     curl -v -H "Authorization: token ${GITHUB_TOKEN}" -L https://raw.githubusercontent.com/NEEDGITGOOD/Terraform_IaC/main/Digital_Ocean/Docker/ProvisionTest_Cloud_Init/docker-compose_docker03.yaml -o /root/docker-compose.yaml
   permissions: '0700'
runcmd:
 - /root/setup.sh
 - sudo ufw allow 3000
 - sudo ufw allow 80
 - sudo ufw allow 53
 - docker compose -f /root/docker-compose.yaml up -d
 - systemctl stop systemd-resolved
 - systemctl disable systemd-resolved
 - docker compose -f /root/docker-compose.yaml up -d

