#cloud-config
package_update: true
package_upgrade: true
runcmd:
 - 'curl -H "Authorization: token ${GITHUB_TOKEN}" -L https://raw.githubusercontent.com/NEEDGITGOOD/Terraform_IaC/main/Digital_Ocean/Docker/ProvisionTest_Cloud_Init/cloud-init_docker02.yaml -o /root/docker-compose.yaml'
  - docker compose -f /root/docker-compose.yaml up -d