#cloud-config
package_update: true
package_upgrade: true
packages:
 - autossh
 - httpie
write_files:
 - path: /root/setup.sh
   content: |
     #!/bin/bash
     echo "Running setup..."
     echo $GITHUB_TOKEN
     curl -H "Authorization: token ${GITHUB_TOKEN}" -L https://raw.githubusercontent.com/NEEDGITGOOD/Terraform_IaC/main/Digital_Ocean/Docker/ProvisionTest_Cloud_Init/templates/docker-compose-portainer.yaml -o /root/docker-compose.yaml
   permissions: '0700'
runcmd:
 - echo "Allowing ports 9000 and 2374!"
 - sudo ufw allow 9000
 - sudo ufw allow 2374
 - echo "Creating ssh directory!"
 - mkdir -p /root/.ssh
 - echo "Running the setup script!"
 - /root/setup.sh
