#cloud-config
package_update: true
package_upgrade: true
write_files:
 - path: /root/setup.sh
   content: |
     #!/bin/bash
     mkdir /root/config
     curl -H "Authorization: token ${GITHUB_TOKEN}" -L https://raw.githubusercontent.com/NEEDGITGOOD/Terraform_IaC/main/Digital_Ocean/Docker/ProvisionTest_Cloud_Init/docker-compose_docker02.yaml -o /root/docker-compose.yaml
     curl -H "Authorization: token ${GITHUB_TOKEN}" -L https://raw.githubusercontent.com/NEEDGITGOOD/Terraform_IaC/main/Digital_Ocean/Docker/ProvisionTest_Cloud_Init/templates/gatus-config.yml -o /root/config/config.yml
   permissions: '0700'
runcmd:
 - /root/setup.sh
 - docker compose -f /root/docker-compose.yaml up -d