#cloud-config
package_update: true
package_upgrade: true
runcmd:
  - echo "Allowing ports 9000 and 2374!"
  - sudo ufw allow 9000
  - sudo ufw allow 2374
  - echo "Creating ssh directory!"
  - mkdir -p /root/.ssh
  - echo "Running the curl command!"
  - 'curl -H "Authorization: token ${GITHUB_TOKEN}" -L https://raw.githubusercontent.com/NEEDGITGOOD/Terraform_IaC/main/Digital_Ocean/Docker/ProvisionTest_Cloud_Init/templates/docker-compose-portainer.yaml -o /root/docker-compose.yaml'

packages:
 - autossh
 - http



 #    
  #    "", # Change the permissions of the ssh file see comment might include this via remote exec
   #   "docker compose -f /root/docker-compose.yml up -d", # Run the docker-compose file
    #  "http POST localhost:9000/api/users/admin/init Username=\"admin\" Password=\"admin01admin01\"" # Create the admin user prob remote exec?

     #     
      #  "chmod +x /root/ssh_tunnels.sh", # Make the script executable
       # "echo Running my Script! command...", # Logging
        #"bash /root/ssh_tunnels.sh" # Run the script

