version: '3.8'
services:
  portainer_agent:
    image: portainer/agent
    container_name: Portainer-Agent
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
  almalinux:
    build:
      context: .
      dockerfile: Dockerfile.alma_linux
    ports:
      - "2222:22" # Map host's port 2222 to container's port 22 for the ssh connection
    container_name: almalinux_ssh
  kalilinux:
    build:
      context: .
      dockerfile: Dockerfile.kali_linux
    ports:
      - "2223:22" # Map host's port 2223 to container's port 22 for the ssh connection
    container_name: kali_ssh
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    ports:
      - "2224:22" # Map host's port 2224 to container's port 22 for the ssh connection
    container_name: ubuntu_ssh
