version: '3.8'
services:
  portainer_agent:
    image: portainer/agent
    container_name: Portainer-Agent
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=myverypogsecurePW_39woriRiddjd3djD3
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=VERYSECUREPASSWORD9857948712978412
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:latest
    container_name: Wordpress
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=VERYSECUREPASSWORD9857948712978412
      - WORDPRESS_DB_NAME=wordpress
  adguardhome:
    image: adguard/adguardhome
    container_name: Adguard-Home
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000/tcp
      - 443:443/tcp
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    restart: unless-stopped
volumes:
  db_data:
