#cloud-config
package_update: true
package_upgrade: true
packages:
 - autossh
 - httpie
write_files:
 - path: /root/setup.sh
   content: |
     #!/bin/bash
     curl -v -L https://raw.githubusercontent.com/NEEDGITGOOD/Terraform_IaC/main/Digital_Ocean/Docker_Infrastructure/docker-compose/docker-compose-portainer.yaml -o /root/docker-compose.yaml
   permissions: '0700'
 - path: /root/setupDocker01IP.sh
   content: |
     #!/bin/bash
     DOCKER01_IP=$(hostname -I | cut -d' ' -f1)
     sed -i "s/PLACEHOLDER_DOCKER01_IP_PUBLIC_ADDRESS/$${DOCKER01_IP}/" /root/config/config.yml
   permissions: '0700'
runcmd:
# - sudo ufw allow 9443
# - sudo ufw allow 80
 - mkdir -p /root/.ssh
 - mkdir -p /root/config
 - /root/setup.sh
 - DOCKER01_IP=$(hostname -I | cut -d' ' -f1)
 - sed -i "s/PLACEHOLDER_DOCKER01_IP_PUBLIC_ADDRESS/$${DOCKER01_IP}/" /root/my-config.yml