endpoints:

### Docker01

  - name: 0_Docker01
    url: "icmp://PLACEHOLDER_DOCKER01_IP_PUBLIC_ADDRESS"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"


  - name: 1_Portainer01 
    url: "https://PLACEHOLDER_DOCKER01_IP_PUBLIC_ADDRESS:9443"
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"        

  - name: 2_Monitoring01                
    url: "http://PLACEHOLDER_DOCKER01_IP_PUBLIC_ADDRESS:8080"
    interval: 1m
    conditions:
      - "[STATUS] == 200"         

  - name: 3_Dashboard01               
    url: "http://PLACEHOLDER_DOCKER01_IP_PUBLIC_ADDRESS"
    interval: 1m
    conditions:
      - "[STATUS] == 200"         

### Docker02

  - name: 4_Docker02
    url: "icmp://PLACEHOLDER_DOCKER02_IP_PUBLIC_ADDRESS"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: 5_Ubuntu01 - Ubuntu Machine
    url: "tcp://PLACEHOLDER_DOCKER02_IP_PUBLIC_ADDRESS:2222"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: 6_Alma01 – Alma Linux Machine
    url: "tcp://PLACEHOLDER_DOCKER02_IP_PUBLIC_ADDRESS:2223"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: 7_Attackbox01 - Kali
    url: "tcp://PLACEHOLDER_DOCKER02_IP_PUBLIC_ADDRESS:2224"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

### Docker03

  - name: 8_Docker03
    url: "icmp://PLACEHOLDER_DOCKER03_IP_PUBLIC_ADDRESS"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: 9_Wordpress01 - Wordpress               
    url: "http://PLACEHOLDER_DOCKER03_IP_PUBLIC_ADDRESS:8080"
    interval: 1m
    client:
      insecure: true
      timeout: 30s
    conditions:
      - "[STATUS] == 200"

  - name: 10_DNS01 – ADGuard              
    url: "http://PLACEHOLDER_DOCKER03_IP_PUBLIC_ADDRESS:80"
    interval: 1m                  
    conditions:
      - "[STATUS] == 200"         
    timeout: 30s  

  - name: 11_DNS - AdGuard - DNS A Request
    url: "PLACEHOLDER_DOCKER03_IP_PUBLIC_ADDRESS"
    interval: 5m
    dns:
      query-name: "google.de"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"

### VPN01 - OpenVPN

  - name: 12_VPN01 - OpenVPN Access Server
    url: "icmp://207.154.228.93"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

### NGINX & Loadbalancer

  - name: 13_Nginx01 Webserver
    url: "icmp://PLACEHOLDER_NGINX01_IP_PUBLIC_ADDRESS"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: 14_Nginx02 Webserver
    url: "icmp://PLACEHOLDER_NGINX02_IP_PUBLIC_ADDRESS"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: 15_Loadbalancer Webserver
    url: "icmp://PLACEHOLDER_LOADBALANCER_IP_PUBLIC_ADDRESS"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: 16_Check DNS A Record for Webserver (newworld.icu Domain)
    url: "8.8.8.8"
    interval: 1m
    dns:
      query-name: "www.newworld.icu"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"

### Netbox01

  - name: 17_Netbox01
    url: "https://PLACEHOLDER_NETBOX01_IP_PUBLIC_ADDRESS"
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"

### HoneyPot

  - name: 18_HoneyPot
    url: "icmp://167.71.240.4"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"