endpoints:
- name: example-dns-query
    url: "8.8.8.8" # Address of the DNS server to use
    interval: 5m
    dns:
      query-name: "example.com"
      query-type: "A"
    conditions:
      - "[BODY] == 93.184.216.34"
      - "[DNS_RCODE] == NOERROR"

  - name: docker01
    url: "icmp://PLACEHOLDER_DOCKER01_IP_PUBLIC_ADDRESS"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: docker02
    url: "icmp://PLACEHOLDER_DOCKER01_IP_PUBLIC_ADDRESS"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: docker03
    url: "icmp://PLACEHOLDER_DOCKER01_IP_PUBLIC_ADDRESS"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"